### PR TITLE
fix duplicate strings with Vosk

### PR DESCRIPTION
**Pull request by 88fingerslukee**
as per this discussion here:

https://community.jitsi.org/t/jigasi-transcription-with-vosk-repeated-lines/91573/13

### CODE REVIEW

**Comment by damencho** [comment]
Hi, thanks for your contribution!
If you haven't already done so, could you please make sure you sign our CLA (https://jitsi.org/icla for individuals and https://jitsi.org/ccla for corporations)? We would unfortunately be unable to merge your patch unless we have that piece :(.

**Review by damencho — APPROVED** [review]

**Comment by 88fingerslukee** [comment]
> Hi, thanks for your contribution!
> If you haven't already done so, could you please make sure you sign our CLA (https://jitsi.org/icla for individuals and >https://jitsi.org/ccla for corporations)? We would unfortunately be unable to merge your patch unless we have that piece :(.

No worries. I have signed both.

**Comment by damencho** [comment]
Mind that what you signed doesn't match your GitHub name nor your email used for the GitHub commit. There is no way to match it. I will proceed and merge this one char change anyway ... but for future changes, you will need to modify those docs or re-sign again.

**Comment by rpgresearch** [comment]
This is also not working for us. Still shows it "thinking" through the words, so shows several lines at once. Is there any one to configure this through any configuration or api calls? Or is only fixable through customizing the source and custom compiling?
Did this fix get incorporated into current core?
Really want to avoid manual compile/forking if possible, prefer to try to stick with Jitsi's core so easier to maintain for all of us just being volunteers.
Can someone advise what status is for this to be fixed? We work a lot with Deaf and Hard of Hearing and really need to get this working. We will gladly test and provide feedback if it would help.
Thanks!

**Comment by rpgresearch** [comment]
If this is considered a different issue let me know and I'll post as a new issue. I was trying to avoid a duplicate issue, but since this is listed as closed I'm not sure how you would prefer this be handled. Thanks for any suggestions @damencho @nshmyrev

**Comment by damencho** [comment]
This had been merged and is in since version jigasi_1.1-174-gdf364fe-1_amd64.deb

**Pull request merged**
