### PR TITLE
feat: drop jigasi callers without web users

### PR DESCRIPTION
**Pull request by jerry2013**
I use jigasi in a special "mode" where after all web users have left, all jigasi calls need to be dropped automatically.

I'm proposing this change so that I don't have to build my own all the time but I'm not sure if it's acceptable by the jitsi community.

### CODE REVIEW

**Comment by damencho** [comment]
Hi, thanks for your contribution!
If you haven't already done so, could you please make sure you sign our CLA (https://jitsi.org/icla for individuals and https://jitsi.org/ccla for corporations)? We would unfortunately be unable to merge your patch unless we have that piece :(.

**Comment by damencho** [comment]
I'm wondering about some other name of the option? ... The default is a little bit confusing with the double negative ... disallow_only = false ... WDYT?

**Comment by jerry2013** [comment]
Yeah, I wrecked my brain on a name that is clear, but could not come up with anything clear - I'm totally open to ideas.

Maybe JIGASI_ONLY_MEETING (default truthy)? or STOP_MEETING_WITHOUT_WEB (default falsy)?

**Comment by damencho** [comment]
Yeah, maybe rename it to "org.jitsi.jigasi.ALLOW_ONLY_JIGASIS_IN_ROOM" and that defaults to true.

**Comment by jerry2013** [comment]
sorry for the delay - updated to ALLOW_ONLY_JIGASIS_IN_ROOM - and listed such in the config template

**Review by damencho — APPROVED** [review]

**Pull request merged**
