### PR TITLE
Fix SDP origin Request

### PR DESCRIPTION
**Pull request by joshelson**
This resolves an issue with PJSIP compatibility where the origin header on outbound SIP invites was invalid per RFC.  This resolves the issue.

Also added a couple minor Readme notes to assist people just building this for the first time.

### CODE REVIEW

**Comment by Fohdeesha** [comment]
will this ever be merged? outgoing calling is basically broken without this PR, I get a constant "Error parsing/validating SDP body: Invalid SDP origin line (PJMEDIA_SDP_EINORIGIN)" error in asterisk trying to use Jigasi

**Comment by damencho** [comment]
I din't found signed CLA from @joshelson, so I bumped the java-sdp-nist-bridge version myself. Could you please test build 108, @Fohdeesha ?

**Comment by Fohdeesha** [comment]
I bumped it up on my own clone of the repo last night and it instantly fixed it, working great now with the 1.2 java sdp bridge. Can we expect an updated debian package with this anytime soon? Compiling it from source was a bit of a PITA on some systems. Thanks!

**Comment by damencho** [comment]
It's already there. https://download.jitsi.org/unstable/

**Comment by Fohdeesha** [comment]
sweet! thanks so much. working great

**Pull request closed without merging**
